name: Deploy Function App
on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd api
          npm ci
      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: logocraftfunctions
          # This secret will be provided by GitHub when the workflow runs
          # The linter warning "Context access might be invalid" can be safely ignored
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: api
