name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: logocraftfunctions
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      working-directory: api
      run: npm ci

    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: api
        # This secret will be provided by GitHub when the workflow runs
        # The linter warning "Context access might be invalid" can be safely ignored
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
