name: Deploy Azure Infrastructure (Simplified)

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: 'LogoCraftRG' # Single Resource Group
  LOCATION: 'eastus' # Define default location, can be overridden by parameter

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Resource Group
      uses: azure/cli@v1
      with:
        inlineScript: |
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
    
    - name: Deploy Simplified Infrastructure (main.bicep)
      uses: azure/arm-deploy@v1
      with:
        deploymentName: github-swa-${{ github.run_number }}
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./infrastructure/main.bicep
        parameters: >
          location=${{ env.LOCATION }}
          namePrefix=logocraft
          # staticWebAppName, staticWebAppSkuName, storageAccountName use defaults from main.bicep if not provided
          # Or they can be explicitly passed here if needed:
          # staticWebAppName=logocraftswa${{ github.run_number }} 
          # storageAccountName=logocraftst${{ github.run_number }}

    # Optional: Get outputs from the deployment if needed by other jobs or for notification
    - name: Get outputs from deployment
      id: mainDeployOutput
      if: always() # Run even if previous steps fail, to capture output or error
      run: |
        DEPLOYMENT_OUTPUTS=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name github-swa-${{ github.run_number }} --query properties.outputs -o json)
        echo "Deployment outputs: $DEPLOYMENT_OUTPUTS"
        # Example to set a specific output:
        # SWA_HOSTNAME=$(echo $DEPLOYMENT_OUTPUTS | jq -r '.staticWebAppDefaultHostName.value')
        # echo "staticWebAppDefaultHostName=$SWA_HOSTNAME" >> $GITHUB_OUTPUT
